#!/usr/bin/env perl

use warnings;
use strict;

our $DEBUG=0;

use File::Basename;
use lib dirname(__FILE__);
require ParseEventData;


# We need this here because some modules (like DataStore) expect to find $DEBUG in the $main:: scope

ParseEventData::main();
