{
 "title": "Hosts View",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "K8S Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "8180",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode, instance) (irate(node_cpu_seconds_total{instance=\"ieatrcx8180-priv:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "8181",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,mode) (irate(node_cpu_seconds_total{mode!=\"idle\",instance=\"ieatrcx8181-priv:9100\"}[3m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "8182",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode, instance) (irate(node_cpu_seconds_total{instance=\"ieatrcx8182-priv:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "8183",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode, instance) (irate(node_cpu_seconds_total{instance=\"ieatrcx8183-priv:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "VM Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "8177",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode, instance) (irate(node_cpu_seconds_total{instance=\"ieatrcx8177-priv:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "8178",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode, instance) (irate(node_cpu_seconds_total{instance=\"ieatrcx8178-priv:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "8176",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode, instance) (irate(node_cpu_seconds_total{instance=\"ieatrcx8176-priv:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "8177 Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"ieatrcx8177-priv:9100\"} - node_memory_MemFree_bytes{instance=\"ieatrcx8177-priv:9100\"} - (node_memory_Cached_bytes{instance=\"ieatrcx8177-priv:9100\"} + node_memory_Buffers_bytes{instance=\"ieatrcx8177-priv:9100\"})",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "8178 Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"ieatrcx8178-priv:9100\"} - node_memory_MemFree_bytes{instance=\"ieatrcx8178-priv:9100\"} - (node_memory_Cached_bytes{instance=\"ieatrcx8178-priv:9100\"} + node_memory_Buffers_bytes{instance=\"ieatrcx8178-priv:9100\"})",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "8176 Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"ieatrcx8176-priv:9100\"} - node_memory_MemFree_bytes{instance=\"ieatrcx8176-priv:9100\"} - (node_memory_Cached_bytes{instance=\"ieatrcx8176-priv:9100\"} + node_memory_Buffers_bytes{instance=\"ieatrcx8176-priv:9100\"})",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "8177",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{instance=\"ieatrcx8177-priv:9177\"}[5m])",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "8178 CPU Per VM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{instance=\"ieatrcx8178-priv:9177\"}[5m])",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "8176 CPU Per VM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{instance=\"ieatrcx8176-priv:9177\"}[5m])",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}