{
 "title": "Replication",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ddp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddp\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "ddp2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddp2\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "ddpi",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddpi\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "ddpenm1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddpenm1\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "ddpenm2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddpenm2\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "ddpenm3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddpenm3\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "ddpenm4",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddpenm4\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "ddpenm5",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddpenm5\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "ddpenm6",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddpenm6\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "ddpenm7",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{job=\"replicadb-pods\",app_kubernetes_io_instance=\"ddpenm7\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "InnoDB I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_read{job=\"replicadb-pods\"}[5m])",
     "legendFormat": "r{{app_kubernetes_io_instance}}"
    },
    {
     "expr": "irate(mysql_global_status_innodb_data_written{job=\"replicadb-pods\"}[5m])",
     "legendFormat": "w{{app_kubernetes_io_instance}} "
    }
   ]
  },
  {
   "title": "Repl Volume Disk IOPs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_total{container_name=\"mariadb\",device!=\"/dev/dm-0\",device!=\"/dev/sda\"})",
     "legendFormat": "r{{pod_name}}"
    },
    {
     "expr": "irate(container_fs_writes_total{container_name=\"mariadb\",device!=\"/dev/dm-0\",device!=\"/dev/sda\"})",
     "legendFormat": "w{{pod_name}}"
    }
   ]
  },
  {
   "title": "Replication Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dthms" }
   ],
   "targets": [
    {
     "expr": "mysql_slave_status_seconds_behind_master{job=\"replicadb-pods\"}",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Repl Disk Data Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{container_name=\"mariadb\",device!=\"/dev/dm-0\",device!=\"/dev/sda\"})",
     "legendFormat": "r{{pod_name}}"
    },
    {
     "expr": "irate(container_fs_writes_bytes_total{container_name=\"mariadb\",device!=\"/dev/dm-0\",device!=\"/dev/sda\"})",
     "legendFormat": "w{{pod_name}}"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_instance) ( irate(mysql_global_status_commands_total{job=\"replicadb-pods\",command=~\"update*|delete*|insert*|alter*\"}[5m]) )",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Repl Volume Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=\"atrcx3447-priv:9100\",device=\"dm-20\"}[5m]) / rate(node_disk_reads_completed_total{instance=\"atrcx3447-priv:9100\",device=\"dm-20\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=\"atrcx3447-priv:9100\",device=\"dm-20\"}[5m]) / rate(node_disk_writes_completed_total{instance=\"atrcx3447-priv:9100\",device=\"dm-20\"}[5m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_queries{job=\"replicadb-pods\"}[5m])",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(mysql_global_status_slow_queries{job=\"replicadb-pods\"}[5m])",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Selects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_commands_total{job=\"replicadb-pods\",command=\"select\"}[5m])",
     "legendFormat": "{{app_kubernetes_io_instance}}"
    }
   ]
  }
 ]
}