#!/usr/bin/env perl

use warnings;
use strict;

use File::Basename;
use lib dirname(__FILE__);
require ParseMOs;

# We need this here because some modules (like DataStore) expect to find $DEBUG in the $main:: scope
our $DEBUG=0;

ParseMOs::main();
