#!/bin/bash

ANALYSIS_BIN=`dirname $0`
ANALYSIS_BIN=`cd ${ANALYSIS_BIN} ; cd .. ; pwd`

while getopts s:d:i:o:t:u:r: OPT ; do
    case $OPT in
        s) SITE="${OPTARG}" ;;
        d) DASH_DATE="${OPTARG}" ;;
        i) DATADIR="${OPTARG}" ;;
        o) ANALYSIS_OUTPUT="${OPTARG}" ;;
        t) ANALYSIS_TYPE="${OPTARG}" ;;
        u) UTC_OFFSET="${OPTARG}" ;;
        r) SERVER="${OPTARG}" ;;
    esac
done

if [ -z "${TMP_DIR}" ] ; then
    export TMP_DIR=/data/tmp
fi

if [ -z "${INCR_DIR}" ] ; then
    export INCR_DIR=${TMP_DIR}/incr
fi

export TMP_DIR=${TMP_DIR}/${SERVER}
if [ ! -d ${TMP_DIR} ] ; then
    mkdir ${TMP_DIR}
fi
export INCR_DIR=${INCR_DIR}/${SERVER}
if [ ! -d ${INCR_DIR} ] ; then
    mkdir ${INCR_DIR}
fi

DATE=$(echo "${DASH_DATE}" | sed 's/-//g')
SQL_DATE=`echo ${DASH_DATE} | sed 's/\([0-9]*\)-\([0-9]*\)-\([0-9]*\)/20\3-\2-\1/g'`

# If the log format has not been declared above me, assume default
# for a description of log line formats, see comments in outputProcessing.awk
[ -z "$LOG_LINE_FORMAT" ] && LOG_LINE_FORMAT="s"
export ANALYSIS_BIN SITE DATE LOG_LINE_FORMAT
. ${ANALYSIS_BIN}/common/functions.sh

REMOTEHOSTNAME=${SERVER}
HOST_DIR=${DATADIR}/eo_servers/${SERVER}/${DATE}
TYPE=OTHER
log "Analysing ${SERVER} - type ${TYPE}"
run ${ANALYSIS_BIN}/server/analyseServer -i ${HOST_DIR}/server -o ${ANALYSIS_OUTPUT}/servers \
    -s ${SITE} -d ${SQL_DATE} -t ${TYPE} -a ${DATADIR} -m ${ANALYSIS_TYPE}

HOSTNAME_ONLY=$(echo "${REMOTEHOSTNAME}" | awk -F\. '{print $1}')
if [ -d ${HOST_DIR}/instr ] && [ -s ${HOST_DIR}/instr.txt ] ; then
    run ${ANALYSIS_BIN}/modelled/instr/parseModeledInstr \
        --model ${ANALYSIS_BIN}/modelled/instr/models/common --model ${ANALYSIS_BIN}/modelled/instr/models/EO \
        --cfg ${HOST_DIR}/instr --data ${HOST_DIR}/instr.txt --incr ${INCR_DIR}/parseModeledInstr \
        --site ${SITE} --server ${HOSTNAME_ONLY} --date ${SQL_DATE}
fi

run ${ANALYSIS_BIN}/EO/processEoData -s ${SITE} -d ${DASH_DATE} -h ${HOST_DIR} \
                      -o ${ANALYSIS_OUTPUT} -u ${UTC_OFFSET} -t FULL -r ${HOSTNAME_ONLY}
