#!/usr/bin/env perl

use warnings;
use strict;

use File::Basename;
use lib dirname(__FILE__);
require ParseInstrDump;


# We need this here because some modules (like DataStore) expect to find $DEBUG in the $main:: scope
our $DEBUG=0;

ParseInstrDump::main();
