#!/bin/sh

CONFIG=$1
if [ -z "${CONFIG}" ]; then
    echo "Usage: $0 configfile"
    exit 1
fi

. ${CONFIG}

ROOT_DIR=${DATA_DIR}

NUM_DAYS=90
if [ ! -z $2 ] ; then
    NUM_DAYS=$2
fi

READ_ONLY=0
if [ ! -z $3 ] ; then
    READ_ONLY=1
fi
SITES=`cat ${DATA_DIR}/sitelist.txt`

for SITEDATA in ${SITES}; do    
    SITE_NAME=`echo $SITEDATA | sed 's/^\(.*\):\(.*\)$/\2/g'`
    SITE_DIR=`echo $SITEDATA | sed 's/^\(.*\):\(.*\)$/\1/g'`
    echo "Processing ${SITE_NAME}"

    cd ${ROOT_DIR}/${SITE_NAME}/data
    DIRS=`find . -maxdepth 1 -type d -mtime +${NUM_DAYS}  | egrep '\/[0-9]{6,6}'`
    for DIR in $DIRS; do
        DATE=`echo ${DIR} | sed 's/.*\/\([0-9]*\)$/\1/g'`
	YEAR=`echo ${DATE} | sed 's/[0-9]{4,4}\([0-9]{2,2}\)/\1/g'`
#	if [ -f ${ARCHIVE_DIR}/${SITE_DIR}/OSS_Data_${DATE}.tar.gz -o -f ${ARCHIVE_DIR}/${SITE_DIR}/RANOS_Data_${DATE}.tar.gz ]; then
	if [ 1 -eq 1 ] ; then
	    if [ ${READ_ONLY} -eq 0 ] ; then
		echo "Removing ${DATE}"
		/bin/rm -rf ${DIR}
	    else
		echo "Matched ${DATE}"
	    fi
        else
	    echo "Compressing/Moving ${DATE}"
	    tar cf ${DATA_FILE}_${DATE}.tar ${DATE}
	    gzip ${DATA_FILE}_${DATE}.tar
	    if [ $? -eq 0 ]; then
	       /bin/rm -rf ${DAY_DIR}
	    fi
            /bin/mv ${DATA_FILE}_${DATE}.tar.gz ${ARCHIVE_DIR}/${SITE_DIR}
	fi
    done
done

