#!/usr/bin/env perl

use strict;
use Getopt::Long;
use DBI;
use StatsDB;

our $DEBUG = 0;

main();

sub main
{
    my ($site,$server);
    my @disks = ();

    my $result = GetOptions(
	"site=s" => \$site,
	"server=s" => \$server,
	"disks=s{,}"  => \@disks,
	"debug=s" => \$DEBUG
	);	   
    ( $result == 1 ) or die "Invalid Args";

    setStatsDB_Debug($DEBUG); 
    my $dbh = connect_db();

    my $siteId = getSiteId($dbh,$site);
    my $serverId = getServerId($dbh,$siteId,$server);
    my $r_diskMap = getIdMap($dbh, "disks", "id", "name", \@disks, $serverId, "serverid" );
    
    foreach my $disk ( @disks ) {
	printf "DISK_ID %d %s\n", $r_diskMap->{$disk}, $disk;
    }

    $dbh->disconnect;
}
