#!/usr/bin/env perl

use warnings;
use strict;

use File::Basename;
use lib dirname($0);
use ParseFLS;

# We need this here because some modules (like DataStore) expect to find $DEBUG in the $main:: scope
our $DEBUG=0;

ParseFLS::main();
