#!/usr/bin/env perl
# WI 1.36, 

use Getopt::Long;
use strict;
use Data::Dumper;
use StatsDB;
use DBI;
use StatsTime;

our $site;
our $DEBUG = 0;
our $bcpFile;

sub main {
    my ($systemLog, $date);
    my $result = GetOptions (
        "site=s" => \$site,
        "date=s" => \$date,
        "system=s" => \$systemLog,
        "debug=s" => \$DEBUG
    );

    my $tmpDir = "/tmp";
    if ( exists $ENV{"TMP_DIR"} ) { $tmpDir = $ENV{"TMP_DIR"}; }
    $bcpFile = $tmpDir . "/gpi_stats.bcp";
    parseLog($systemLog, $date);
}

sub parseLog {
    my $systemLog = shift;
    my $date = shift;
    my $dbh = connect_db();
    my $siteId = getSiteId($dbh, $site);
    open SYSTEM_LOG, $systemLog or die "Could not load system log file" . $systemLog . ": " . $!;
    open BULK_INSERT, ">$bcpFile" or die "Could not open bulk insert file " . $bcpFile . ": " . $!;
    while ( my $line = <SYSTEM_LOG> ) {
        if ($line =~ /^$date ([0-2][0-9]):([0-5][0-9])\.([0-5][0-9]) MAF_Server "GeranPlugIn\.SynchroniseBTS" "COARSE" (.*)/) {
            my $hr = $1; my $min = $2; my $sec = $3; my $rest = $4;
            if ($DEBUG > 6) { print "Matched line : " . $rest . "\n"; }
            if ($rest =~ /"GPI Synch, Start Time:\s*(20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]) ([0-2][0-9]):([0-5][0-9]):([0-5][0-9])\.([0-9][0-9][0-9]), (.*)/) {
                my $startDate = $1; my $startHour = $2; my $startMin = $3; my $startSec = $4; my $startMSec = $5; $rest = $6;
                if ($DEBUG > 6) { print "Matched start, left: " . $rest . "\n"; }
                if ($rest =~ /End Time: (20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]) ([0-2][0-9]):([0-5][0-9]):([0-5][0-9])\.([0-9][0-9][0-9]), (.*)/) {
                    my $endDate = $1; my $endHour = $2; my $endMin = $3; my $endSec = $4; my $endMSec = $5; $rest = $6;
                    if ($DEBUG > 6) { print "Matched end, left: " . $rest . "\n"; }
                    if ($rest =~ /BTSadded:\s*(\d+),\s*BTSremoved:\s*(\d+),\s*BTSmodified:\s*(\d+),\s*AssocCreated:\s*(\d+),\s*AssocRemoved:\s*(\d+),\s*CabiCreated:\s*(\d+),\s*CabiRemoved:\s*(\d+)"/) {
                        printf(BULK_INSERT "%d\t%s\t%s\t%d\t%d\t%d\t%d\t%d\t%d\t%d\n",
                            $siteId,
                            $startDate . " " . $startHour . ":" . $startMin . ":" . $startSec,
                            $endDate . " " . $endHour . ":" . $endMin . ":" . $endSec,
                            $1, $2, $3, $4, $5, $6, $7
                        );
                    }
                }
            }
        }
    }
    close SYSTEM_LOG;
    close BULK_INSERT;
    # We're almost certain to be guaranteed that the end time is on the same day as the current date
    # only case that can be different is where the event ended just before midnight and was inserted just after midnight
    my $sql = "DELETE FROM gpi_events WHERE siteid = " . $siteId .
        " AND end_time BETWEEN '" . $date . " 00:00:00' AND '" . $date . " 23:59:59'";
    dbDo($dbh,$sql);
    dbDo($dbh,"LOAD DATA LOCAL INFILE \'$bcpFile\' INTO TABLE gpi_events");
}

main;
